config/routes.rb
Rails.application.routes.draw do
  resources :blogs do # doとendを忘れないこと！
    resources :versions, only: %i[index show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_paper_trail #paper_trailを使うと宣言
  has_many :versions
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @version = @blog.versions
    # binding.pry
    # .find(params[:version_id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_blog, only: %i[index show]
    
  def index
    @blog = Blog.find(params[:blog_id])
    @version = @blog.versions
    #TODO:versionsが定義されてないのは何で？　=>　アソシエーション設定忘れ
  end

  def show
    @version = @blog.versions
    # .find(params[:id])
  end

  private

  def set_blog
    @blog = Blog.find(params[:blog_id])
    # ここで(params[:id])とすると、versions_controller内なので:version_idになってしまう
  end

  def version_params
    params.require(:version).permit(:name, :content, :blog_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.hidden_field :title, id: :post_title %>
    <trix-editor input="post_title"></trix-editor>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.hidden_field :content, id: :post_content %>
    <trix-editor input="post_content"></trix-editor>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= sanitize blog.title %></td>
        <td><%= sanitize blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= sanitize @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= sanitize @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<%= link_to 'Version', blog_versions_path(@blog) %>

app/views/blogs/versions/show.html.erb
<h1>Versions#show</h1>
<p>Find me in app/views/versions/show.html.erb</p>


<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to "\"#{@blog.name}\"へ戻る", blog_path(@blog) %>
    </div>
    <h1 class="font-weight-bold mb-4">
      差分を表示する
    </h1>
    <% @version.changeset.keys.select { |key| %w[name content].include?(key) }.each do |key| %>
      <div class="mb-4">
        <h3 class=font-weight-bold">
          <%= Blog.human_attribute_name(key) %>
        </h3>
        <div>
          <%= raw Markdiff::Differ.new.render(*@version.changeset[key]) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentManagementBeta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/versions/index.html.erb
<h1>Versions#show</h1>
<p>Find me in app/views/versions/show.html.erb</p>


<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%#= link_to "\"#{@blog.name}\"へ戻る", blog_path(@blog) %>
    </div>
    <h1 class="font-weight-bold mb-4">
      差分を表示する
    </h1>
    <% @version.each do |version| %>
      <% version.changeset.keys.select { |key| %w[name content].include?(key) }.each do |key| %>
        <div class="mb-4">
          <h3 class="font-weight-bold">
            <%= Blog.human_attribute_name(key) %>
          </h3>
          <div>
            <%= raw Markdiff::Differ.new.render(*@version.changeset[key]) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/versions/show.html.erb
<h1>Versions#show</h1>
<p>Find me in app/views/versions/show.html.erb</p>


<div class="row justify-content-md-center">
  <div class="col-8 p-4">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to "\"#{@blog.name}\"へ戻る", blog_path(@blog) %>
    </div>
    <h1 class="font-weight-bold mb-4">
      差分を表示する
    </h1>
    <% @version.changeset.keys.select { |key| %w[name content].include?(key) }.each do |key| %>
      <div class="mb-4">
        <h3 class="font-weight-bold">
          <%= Blog.human_attribute_name(key) %>
        </h3>
        <div>
          <%= raw Markdiff::Differ.new.render(*@version.changeset[key]) %>
        </div>
      </div>
    <% end %>
  </div>
</div>